### ISSUE TITLE
Data volume can fill up causing dockerd to crash on boot

### ISSUE THREAD

**Issue by jsierles** [superfly/rchab#5]
We found some cases of this in builder app logs. We should probably:

* Prune on more regular intervals instead of only at startup
* Wipe the data volume if disk is completely full and unable to prune
* Figure out why disks are filling up

**Comment by jeromegn** [comment]
> * Prune on more regular intervals instead of only at startup

Builders are stopped all the time, so they start often and so running it on startup seems like it should be enough? Have you seen a different behaviour? Perhaps the prune logic is broken.

> * Wipe the data volume if disk is completely full and unable to prune

Didn't know that could happen. Can we catch that error when it can't prune?

> * Figure out why disks are filling up

Part of this is because buildpacks create a lot of extra containers and volumes.

**Comment by jsierles** [comment]
Pruning may not always do the job, but there could be cases where people are doing a succession of frequent builds, not allowing the builder to idle. I did this once while testing. Of course, just a theory. Pruning seems to work based on logs that print out the disk savings.

Sorry - the problem isn't that it can't prune. The problem is that `dockerd` won't start at all with a full disk. It may be a case where the disk is almost full, then one build pushes it to the limit. At that point, we don't prune, we shut down. Then at startup, dockerd can't boot. So, maybe pruning on shutdown would help.

**Comment by jeromegn** [comment]
> Pruning may not always do the job, but there could be cases where people are doing a succession of frequent builds

We could also prune between each build when we receive the SIGUSR1 signal. That's sent by our web app as soon as we get a new build request to keep the remote builder alive.

> So, maybe pruning on shutdown would help.

That's a good idea!

I think doing both of these extra prunes might help a lot!
